version: '3'
services:
  lelbuild:
    ports:
      - "80"
    build:
      context: src/LelBuild
      dockerfile: Dockerfile.prod
  lelapi:
    ports:
      - "80"
    depends_on:
      - mssql-server-linux
      - mongo
    links:
      - mssql-server-linux:mssql
      - mongo
    build:
      context: src/LelApi
      dockerfile: Dockerfile.prod
  lelconsumer:
    build:
      context: src/LelConsumer
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
  lelflow:
    build:
      context: src/LelFlow
      dockerfile: Dockerfile.prod
    depends_on:
      - lelbuild
      - lelx
      - consul
    links:
      - lelbuild
      - lelx
      - consul  
  lelmongoaggregator:
    build:
      context: src/LelMongoAggregator
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
      - rabbitmq
    links:
      - mongo
      - rabbitmq
  lelsqlaggregator:
    build:
      context: src/LelSqlAggregator
      dockerfile: Dockerfile.prod
    depends_on:
      - mssql-server-linux
      - rabbitmq
    links:
      - mssql-server-linux:mssql
      - rabbitmq
  lelx:
    build:
      context: src/LelX
      dockerfile: Dockerfile.prod
    ports:
      - "80"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    ports:
     - "8005:15672"
     - "5672"
  mssql-server-linux:
    image: microsoft/mssql-server-linux
    ports:
    - "1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Elo_benc1!"
  mongo:
    image: mongo
    ports:
     - "27017"
  consul:
    image: consul
    ports:
     - "8500"
